### ISSUE TITLE
The method that the code depends on

### ISSUE THREAD

**Issue by Dr-Yongqiang** [AhmedDhahri/PCL_Hole_Detection#1]
Hello Ahmed
First of all, I would thank you for this work and your contribution.I want to ask you a question that you asked.In this code,which method you had used, or maybe a scientific paper or anything you relied on.
Thanks a lot

**Comment by AhmedDhahri** [comment]
Hello,

I used the method introcuced in this paper for boundary point detection (I implemented the angle criterion and the moving average criterion).

Gerhard H. Bendels, Ruwen Schnabel and Reinhard Klein, "Detecting Holes in Point Set Surfaces." Journal of WSCG. 2006, vol. 14, no. 1-3, p. 89-96.

I used Principle componment Analysis for neighbourhood extraction.
Then I used spanning trees to get the hole coutour point chain.

**Comment by Dr-Yongqiang** [comment]
> 
Thanks for your reply.

**Comment by Dr-Yongqiang** [comment]
> Hello,
> 
> I used the method introcuced in this paper for boundary point detection (I implemented the angle criterion and the moving average criterion).
> 
> Gerhard H. Bendels, Ruwen Schnabel and Reinhard Klein, "Detecting Holes in Point Set Surfaces." Journal of WSCG. 2006, vol. 14, no. 1-3, p. 89-96.
> 
> I used Principle componment Analysis for neighbourhood extraction. Then I used spanning trees to get the hole coutour point chain.

Hello
I've read the literature,and i don't really understand the principle of ordering projection points around the central sample point.Could you explain it to me?Thank you.I'm sorry to bother you again.
